name: flow_server
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  shared:
    path: ../shared
#  path: ^1.7.0
  shelf_router: ^1.0.0
dev_dependencies:
  pedantic: ^1.11.0
